language: python

notifications:
  slack: ebayclassifiedsgroup:lH5V2FnojyNCh8X84Qi1FKjk

python:
  - "2.7"

addons:
  apt:
    packages:
    - curl
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER orlo PASSWORD 'password';"
  - psql -c "CREATE DATABASE orlo OWNER orlo;" -U postgres

before_install:
  - pip install -r requirements.txt
  - pip install -r requirements_testing.txt

script:
  - sleep 2
  - python setup.py build
  - py.test
